version: '2'

services:
  turtlebot:
    image: agustinhenze/myrosnode:kinetic-turtlebot
    container_name: turtlebot
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp:/tmp
    command: roslaunch turtlebot_gazebo turtlebot_world.launch world_file:=worlds/willowgarage.world gui:=false

  mynode:
    image: agustinhenze/myrosnode:kinetic-turtlebot-intel
    container_name: mynode
    environment:
      - "ROS_HOSTNAME=mynode"
      - "ROS_MASTER_URI=http://turtlebot:11311"
    volumes:
      - $PWD:/mynode
    command: bash -c "cd /mynode/catkin_ws && catkin_make && catkin_make install && . devel/setup.bash && rosrun mynode path_logger.py"
